name: CI Local

on:
  workflow_dispatch:
  push:
    branches: [ "ci-local" ]

jobs:
  ci-local:
    name: ci-local
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PYTHONUNBUFFERED: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install system dependencies (for e2e)
        run: |
          if command -v sudo >/dev/null 2>&1; then
            sudo apt-get update && sudo apt-get install -y --no-install-recommends psmisc curl
          else
            apt-get update && apt-get install -y --no-install-recommends psmisc curl
          fi

      - name: Run ci-local target
        run: make ci-local

